'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Shield, Lock, Hash, CheckCircle2 } from 'lucide-react';

export default function FairPlayPage() {
  return (
    <div className="min-h-screen bg-background p-6">
      <div className="max-w-7xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold flex items-center justify-center gap-2">
            <Shield className="w-10 h-10" />
            Fair Play Policy
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Learn how we ensure fair and transparent gaming for all players
          </p>
        </div>

        {/* Provably Fair System */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Hash className="w-6 h-6" />
              Provably Fair System
            </CardTitle>
            <CardDescription>
              Understanding how our games ensure randomness and fairness
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="space-y-2">
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <span className="text-xl font-bold">1</span>
                </div>
                <h3 className="font-medium">Server Seed</h3>
                <p className="text-sm text-muted-foreground">
                  A random seed is generated by our server for each game round
                </p>
              </div>
              <div className="space-y-2">
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <span className="text-xl font-bold">2</span>
                </div>
                <h3 className="font-medium">Client Seed</h3>
                <p className="text-sm text-muted-foreground">
                  Players can provide their own seed to influence the outcome
                </p>
              </div>
              <div className="space-y-2">
                <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center">
                  <span className="text-xl font-bold">3</span>
                </div>
                <h3 className="font-medium">Verification</h3>
                <p className="text-sm text-muted-foreground">
                  Results can be verified using our open-source algorithm
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Game-Specific Rules */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card>
            <CardHeader>
              <CardTitle>Aviator Game</CardTitle>
              <CardDescription>How fairness is ensured in Aviator</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Random Multiplier</h4>
                  <p className="text-sm text-muted-foreground">
                    Each game's multiplier is determined by a cryptographic hash function
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Instant Verification</h4>
                  <p className="text-sm text-muted-foreground">
                    Players can verify each round's fairness immediately after completion
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Transparent Odds</h4>
                  <p className="text-sm text-muted-foreground">
                    House edge and winning probabilities are clearly displayed
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Color Game</CardTitle>
              <CardDescription>Fair play mechanics in Color Game</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Random Color Selection</h4>
                  <p className="text-sm text-muted-foreground">
                    Colors are selected using a verifiable random function
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Equal Probabilities</h4>
                  <p className="text-sm text-muted-foreground">
                    Each color has a fixed probability clearly shown to players
                  </p>
                </div>
              </div>
              <div className="flex items-start gap-4">
                <CheckCircle2 className="w-5 h-5 text-green-500 mt-1" />
                <div>
                  <h4 className="font-medium">Result History</h4>
                  <p className="text-sm text-muted-foreground">
                    Complete history of results available for verification
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Security Measures */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Lock className="w-6 h-6" />
              Security Measures
            </CardTitle>
            <CardDescription>
              Additional steps we take to ensure fair play
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <h3 className="font-medium">Anti-Cheating Systems</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Multiple account detection
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Bot prevention measures
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Regular security audits
                  </li>
                </ul>
              </div>
              <div className="space-y-4">
                <h3 className="font-medium">Player Protection</h3>
                <ul className="space-y-2 text-sm text-muted-foreground">
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Responsible gaming limits
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Self-exclusion options
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Transparent transaction history
                  </li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}